spring:
  thymeleaf:
    cache: false    #不使用缓存，热加载
    prefix: classpath:/templates/
    encoding: UTF-8 #编码格式
    suffix: .html   #模板后缀名
    mode: HTML     #html5标准已经被抛弃，请使用html模型
# h2配置项
  h2:
    console:
      enabled: true

#datasource
  datasource:
    url: jdbc:mysql://localhost/blog?userSSL=false&serverTimezone=UTC&characterEncoding=utf-8 #设置jdbc url
    username: root                              #用户名
    password: 123456                            #密码
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动项配置

  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create-drop # 参考https://www.cnblogs.com/qingmuchuanqi48/p/11616145.html
      ddl-auto: update

  #https://blog.csdn.net/ghdqfhw/article/details/113687869
  #采用配置，发现配置还是被丢弃，使用推荐的一些配置
  elasticsearch:
    username: # 用户名
    password: #密码
    connection-timeout: 1s  # 连接超时时间
    socket-timeout: 30s #
    uris: ${ES_HOST:localhost}:${ES_PORT:9200} # 端口位置
