server:
  port: 80

logging:
    level:
      cn.studycarbon: debug

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studycarbon #?servierTimezone=UTC
    username: root
    password: 123456