server:
  port: 80
  tomcat:
    accesslog:
      enabled: true



spring:
  thymeleaf:
    cache: true    #不使用缓存，热加载
    prefix: classpath:/templates/
    encoding: UTF-8 #编码格式
    suffix: .html   #模板后缀名
    mode: HTML     #html5标准已经被抛弃，请使用html模型
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

  # h2配置项
  h2:
    console:
      enabled: true

# datasource
  datasource:
    url: jdbc:mysql://49.232.169.205:3306/blog?userSSL=false&serverTimezone=UTC #设置jdbc url
    username:  root                              #用户名
    password:  te5.$%Yct-Fx/                     #密码
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动项配置

  jpa:
    show-sql: false
    hibernate:
      # ddl-auto: create-drop # 参考https://www.cnblogs.com/qingmuchuanqi48/p/11616145.html
      ddl-auto: update

  # https://blog.csdn.net/ghdqfhw/article/details/113687869
  # 采用配置，发现配置还是被丢弃，使用推荐的一些配置
  elasticsearch:
    username: elastic # 用户名
    password: 123456 # 密码
    connection-timeout: 1s  # 连接超时时间
    socket-timeout: 30s #
    uris: ${ES_HOST:49.232.169.205}:${ES_PORT:9200} # 端口位置

  main:
    allow-circular-references: true

  web:
    resources:
      cache:
        period: 604800
      chain:
        cache: false
        compressed: true
fastdfs:
  # 连接超时
  connect-timeout: 60
  # 读取时间
  so-timeout: 15000
  # 生成缩略图参数
  thumb-image:
    width: 150
    height: 150
  # 支持配置多个
  tracker-list:
    - 103.42.31.49:22122




  # 远程部署参考：https://blog.csdn.net/qq_41473638/article/details/126879439?ops_request_misc=&request_id=&biz_id=102&utm_term=idea%E8%BF%9C%E7%A8%8B%E5%8F%91%E5%B8%83&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-0-126879439.142^v73^insert_down2,201^v4^add_ask,239^v2^insert_chatgpt&spm=1018.2226.3001.4187
debug: true
logging:
  level:
    root: info


